import './globals.css';
import { AuthProvider } from '@/app/providers/AuthContext'; // <-- Importera

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider> {/* <-- Lägg till denna rad */}
          {children}
        </AuthProvider> {/* <-- Och denna rad */}
      </body>
    </html>
  );
}
