'use client'; // AuthProvider använder client-side hooks
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/hooks/useAuth"; // Importera AuthProvider

const inter = Inter({ subsets: ["latin"] });

// Metadata kan inte längre exporteras från en client component. 
// Detta behöver hanteras separat om dynamisk metadata behövs.
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
